version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '&JEDbet2004&'

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
      